homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 33
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  cors_allowed_origins:
    - http://172.16.1.54:7080
    
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
recorder:
  purge_interval: 2
  purge_keep_days: 7
logger:
  default: warning

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

google_domains:
  domain: !secret google_domain
  username: !secret google_username
  password: !secret google_password
  
mqtt:
  broker: core-mosquitto

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://172.16.1.54:3218
  tasmoadmin:
    title: TasmoAdmin
    icon: mdi:lightbulb-on
    url: http://172.16.1.54:9541

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

#image_processing:
# - platform: openalpr_cloud
#   api_key: !secret openalpr_key
#   region: us
#   source:
#    - entity_id: camera.driveway
    
media_player:
  - platform: plex
  
binary_sensor:
  - platform: ring
  
ring:
  username: !secret ring_username
  password: !secret ring_password
  
device_tracker:
  - platform: unifi
    host: 172.16.1.10
    verify_ssl: false
    username: nodered
    detection_time: 600
    password: !secret unifi_password
    new_device_defaults:
      track_new_devices: true
      hide_if_away: true
    ssid_filter:
      - 'MAGRATHEA'
      - 'MAGRATHEA-GUEST'
 
input_number:
  lightbox_transition_speed:
    name: Lightbox Transition Speed
    initial: 150
    min: 1
    max: 150
    step: 10
  theater_transition_speed:
    name: Theater Transition Speed
    initial: 150
    min: 1
    max: 150
    step: 10

sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
